apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ps-demo
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      nodePort: 30432
  selector:
    app: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-admin
  namespace: ps-demo
  labels:
    app: pgadmin
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30300
  selector:
    app: pgadmin