apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ns-grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana