name: Terraform destroy

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    name: Terraform destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1

     - name: Terraform Init
       run: |
        terraform init

     - name: Terraform State
       run: |
        terraform state list

     - name: Terraform Destroy
       run: |
        terraform destroy -auto-approve -input=false -var-file="variables/${{ inputs.environment }}/terraform.tfvars"
