name: Terraform - Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      LOCALIZATION_DOCKERFILE:
        required: true
        type: string

jobs:
  build:
    name: Deploy ECR
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2

     - name: Build, tag, and push image to Amazon ECR
       env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
         IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
         LOCALIZATION_DOCKERFILE: ${{ inputs.LOCALIZATION_DOCKERFILE }}
       run: |
         cd $LOCALIZATION_DOCKERFILE
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG