# Generated by Django 3.2 on 2023-08-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='group_name',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
