# Generated by Django 3.2 on 2023-08-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_amenity_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='description_en',
        ),
    ]
