# Generated by Django 3.2 on 2023-08-31 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230831_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_amenity', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_pl', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='amenity',
            name='group_amenity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.amenitygroup'),
        ),
    ]
